import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Lexend_Deca,Libre_Caslon_Text } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const lexend = Lexend_Deca({
  subsets: ["latin"],
  variable: "--font-lexend",
});
const caslon = Libre_Caslon_Text({
  subsets: ["latin"],
  weight: ["400", "700"], 
  variable: "--font-caslon", 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lexend.variable} ${caslon.variable} antialiased font-lexend`}
      >
        {children}
      </body>
    </html>
  );
}
